name = "coolsculpting-de-new"
compatibility_date = "2025-11-28"
compatibility_flags = ["nodejs_compat"]
build_command = "npx @cloudflare/next-on-pages@latest build"
pages_build_output_dir = ".vercel/output/static"
